Changed CMAKE_*_DIR vars to FLUIDSYNTH_*_DIR (newly created)
FluidSynth/fluidsynth pull request #1040
Opened 2022-01-28 17:49 UTC by devingryu

This change is for compatibility of adding fluidsynth as subdirectory in other cmakefiles.
If fluidsynth is added as subdirectory of other projects, it would produce error since CMAKE_SOURCE_DIR is different from the value when built solely.
I have nothing to complain about even if you don't accept it, but it would be grateful if you consider it.

Thanks in advance.

2022-01-28 18:35 UTC, derselbst commented
@pedrolcl Opinions?

2022-01-28 19:03 UTC, pedrolcl commented
> Opinions?

It is a common use case to embed cmake projects inside other projects, for instance as subdirectories or git submodules. That is why the global-process variables CMAKE_SOURCE_DIR and CMAKE_BINARY_DIR should be avoided. But...

The [project()](https://cmake.org/cmake/help/v3.13/command/project.html) command already defines suitable replacements:
* `PROJECT_SOURCE_DIR`, `${PROJECT_NAME}_SOURCE_DIR`
* `PROJECT_BINARY_DIR`, `${PROJECT-NAME}_BINARY_DIR`

In our case, https://github.com/FluidSynth/fluidsynth/blob/91515b09c45c403bbd5dad84875988b95253f3b9/CMakeLists.txt#L35 the two variables already created are:
* `FluidSynth_SOURCE_DIR`
* `FluidSynth_BINARY_DIR`

Because in cmake, [variable names are case sensitive](https://cmake.org/cmake/help/v3.13/manual/cmake-language.7.html#variables).

By the way, there is still an open issue regarding the `project()` command: #1021

2022-01-28 19:14 UTC, devingryu commented
@pedrolcl Thanks for commenting.
I didn't realized that there are predefined variables in `project()`... Then are you willing to accept the alternative method of using FluidSynth_*_dir variables?

2022-01-28 19:19 UTC, pedrolcl commented
> are you willing to accept the alternative method of using FluidSynth_*_dir variables?

I have no objections.

2022-01-28 19:21 UTC, pedrolcl requested changes
Please reference the already existing variables instead of the new ones that you have created, Thanks!

2022-01-28 19:21 UTC, pedrolcl commented on CMakeLists.txt
> +
In my opinion, there is no need to create those variables, when there are already two created:
* `FluidSynth_SOURCE_DIR`
* `FluidSynth_BINARY_DIR`
These variables are created for every cmake project, when the command [project()](https://cmake.org/cmake/help/v3.13/command/project.html) is called.

2022-01-28 19:22 UTC, derselbst commented
Using FluidSynth_SOURCE_DIR and  FluidSynth_BINARY_DIR sounds good to me as well.

> By the way, there is still an open issue regarding the project() command: #1021

I see no dependency between those two tasks. So, I would prefer to address #1021 separately.

2022-01-28 19:43 UTC, devingryu commented
> Please reference the already existing variables instead of the new ones that you have created, Thanks!

It seems that the build has gone well(except for broken prerequisite links for win builds)! Thanks for letting me know about project variables too. Helped me a lot for my project!

2022-01-29 12:11 UTC, derselbst approved these changes
LGTM, Thanks!

2022-01-29 12:11 UTC, merged