[RFC] Using Sustain Pedal like Soft Pedal
FluidSynth/fluidsynth pull request #1276
Opened 2023-09-08 14:42 UTC by derselbst

This attempt to implement the method described in  #1271.

Unfortunately, it doesn't work. In my tests I've found that manipulating the release time does not affect voices already playing in release phase.

I currently have no time for a deeper investigation.

2023-09-08 14:44 UTC, derselbst commented
@RobsonFBP FYI

2023-09-17 04:03 UTC, RobsonFBP commented
-----
Thanks for this PR.
I liked the name of the created variable ignore_sutain because it is more intuitive than cancel_default_hold.
-----
`        if((mod->src1 == SUSTAIN_SWITCH && mod->flags1 & (FLUID_MOD_CC | FLUID_MOD_SWITCH))
            || (mod->src2 == SUSTAIN_SWITCH && mod->flags2 & (FLUID_MOD_CC | FLUID_MOD_SWITCH))
            && (mod->dest == GEN_VOLENVRELEASE))
        {
            voice->ignore_sustain = 1;
        }`

I think if `(mod->src1 == SUSTAIN_SWITCH)` is true, `mod->flags1 & (FLUID_MOD_CC | FLUID_MOD_SWITCH)` will always be true and could be simplified to:

        if ((mod->src1 == SUSTAIN_SWITCH || mod->src2 == SUSTAIN_SWITCH) && mod->dest == GEN_VOLENVRELEASE)
        {
            voice->ignore_sustain = 1;
        }

I would be even more restrictive using both SUSTAIN_SWITCH sources


        if (mod->src1 == SUSTAIN_SWITCH && mod->src2 == SUSTAIN_SWITCH && mod->dest == GEN_VOLENVRELEASE)
        {
            voice->ignore_sustain = 1;
        }

But if you want to keep the code without simplifying, you could fix the brackets like this.

        if(((mod->src1 == SUSTAIN_SWITCH && mod->flags1 & (FLUID_MOD_CC | FLUID_MOD_SWITCH))
            || (mod->src2 == SUSTAIN_SWITCH && mod->flags2 & (FLUID_MOD_CC | FLUID_MOD_SWITCH)))
            && mod->dest == GEN_VOLENVRELEASE)
        {
            voice->ignore_sustain = 1;
        }

2023-11-13 04:22 UTC, RobsonFBP requested changes
These proposed changes are to create a smooth fit when releasing the key with the sustain pedal depressed. Useful for smooth tuning on instruments that sound indefinitely while the sustain pedal is depressed.

2023-11-13 04:22 UTC, RobsonFBP commented on src/synth/fluid_voice.c
>      }
```suggestion
    else if(fluid_channel_sustained(channel))
    {
        voice->status = FLUID_VOICE_SUSTAINED;        
        //  Here it changes the envelope to simulate ignore_sustain        
        if(voice->note_off_sustain)
        {
            fluid_voice_gen_set(voice, GEN_VOLENVDECAY, voice->note_off_sustain);
            fluid_voice_gen_set(voice, GEN_VOLENVSUSTAIN, 960); 
            fluid_voice_update_param(voice, GEN_VOLENVSUSTAIN); 
        }
    }
```

2023-11-19 17:44 UTC, derselbst commented
Ok, I applied your suggestions, thanks. However, I'm currently unable to test this. It may take me a few weeks before coming back to this.

2024-01-02 17:45 UTC, derselbst commented
I found some time to look into this again. I can confirm that the current change results in an audible manipulation of the sustain and release phases for new voices only (i.e. not for already playing voices). The most noticeable effect is that notes which were played while the sustain pedal was depressed, keep playing even when releasing the pedal afterwards and playing further notes. I'm not quite sure if this is supposed to be the effect intended by the original discussion.

One problem I observed is that fluidsynth easily runs out of polyphone, when playing notes while the pedal is depressed:
`fluidsynth: debug: Polyphony exceeded, trying to kill a voice`

This doesn't happen when playing with the regular sustain pedal behavior and is probably due to decay and release phases being both expanded by the current implementation.

Honestly, I don't really find this behavior intuitive or comprehensive. But I would like to hear what others think about it?

2024-01-29 01:04 UTC, RobsonFBP commented
I would also like to be able to test each change, but I don't know how to do it. If you could send me a compiler with all the settings and all the necessary files and dependencies, so that I could just make the changes and compile, I could perhaps deliver the finished result.

Eu também gostaria de poder testar cada mudança, mas não sei como fazer. Se você pudesse me mandar um compilador com todas as configurações  e todos os arquivos e dependências necessários de modo que eu apenas fizesse as mudanças e compilasse, poderia entregar o resultado pronto.

2024-01-29 22:44 UTC, derselbst commented
The process of compiling is explained in our wiki:
https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake

2024-09-19 11:36 UTC, closed without merging

2024-09-19 11:40 UTC, RobsonFBP commented
Obrigado pela atenção. Grande abraço.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: Tom M. ***@***.***>
Sent: Thursday, September 19, 2024 8:36:35 AM
To: FluidSynth/fluidsynth ***@***.***>
Cc: RobsonFBP ***@***.***>; Mention ***@***.***>
Subject: Re: [FluidSynth/fluidsynth] [RFC] Using Sustain Pedal like Soft Pedal (PR #1276)


Closed #1276<https://github.com/FluidSynth/fluidsynth/pull/1276>.

—
Reply to this email directly, view it on GitHub<https://github.com/FluidSynth/fluidsynth/pull/1276#event-14322634767>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BB7SKYVKLJRITL6HWQUGCC3ZXKZMHAVCNFSM6AAAAAA4QPXBCGVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGMZDENRTGQ3TMNY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-19 12:09 UTC, derselbst commented
Sorry, but this PR stayed open for over a year without a working solution in mind, without activity over the past 8 months. I currently don't see this PR will reach a shape where it can be accepted.